# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: 273do
# "service" is the name of this project. This will also be added to your AWS resource names.
service: thor-web-app-be

custom:
  wsgi:
    app: app.app
    pythonBin: /usr/bin/python3

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any

resources:
  Resources:
    UploadBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: "thor-upload-tmp-data"

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-ignore
